---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timout: 600

    - name: "install python for Ansible."
      become: yes
      apt:
       name: ["python3"]
       state: latest
       update_cache: yes

    - name: "nodejs"
      become: yes
      apt:
        name: ["nodejs"]
        state: latest
        update_cache: yes

    - name: "npm"
      become: yes
      apt:
        name: ["npm"]
        state: latest
        update_cache: yes

    - name: "install pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present




  roles:
    - configure-server.yml 
